{% set name = "xvega-bindings" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-xeus/xvega-bindings/archive/{{ version }}.tar.gz
  sha256: d66cdbde8f23f8e18e8ae4ff9b73adcd1229ada174a04dba8e342c3c95cf3a5b

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - nlohmann_json
    - xtl
    - xvega >=0.0.4
    - xproperty

test:
  commands:
    - test -d ${PREFIX}/include/xvega-bindings  # [unix]
    - test -f ${PREFIX}/include/xvega-bindings/xvega_bindings.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xvega-bindings/xvega-bindingsConfig.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\xvega-bindings\xvega_bindings.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xvega-bindings\xvega-bindingsConfig.cmake (exit 1)  # [win]

about:
  home: https://github.com/jupyter-xeus/xvega-bindings/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: xvega bindings for xeus
  doc_url: https://xeus-sqlite.readthedocs.io/en/latest/xvega_magic.html

extra:
  recipe-maintainers:
    - SylvainCorlay
    - madhur-tandon
    - marimeireles
